### PR TITLE
Ft association

### PR DESCRIPTION
**Pull request by thauma9**
ADD polymorphism to follower/following-like relationships

### CODE REVIEW

**Comment by a-barbieri** [comment]
Please:
- upgrade database instruction

Later:
- update README documentation
- update code documentation

**Comment by thauma9** [comment]
`class CreateBindaRelationships < ActiveRecord::Migration[5.1]
  def change
    create_table :binda_relationships do |t|
      t.integer :parent_related_id
      t.integer :children_related_id
      t.string :parent_related_type
      t.string :children_related_type
      t.timestamps
    end
    add_index :binda_relationships, :parent_related_id
    add_index :binda_relationships, :children_related_id
  end
end`
`class CreateBindaRelatedFields < ActiveRecord::Migration[5.1]
  def change
    create_table :binda_related_fields do |t|

      t.string :name, null: false, uniqueness: true
      t.string :slug, null: false, uniqueness: true
      t.integer :field_setting_id
      t.integer :fieldable_id
      t.string :fieldable_type

    end

    add_index :binda_related_fields, :slug
  end
end
`

**Comment by thauma9** [comment]
`class CreateBindaRelationships < ActiveRecord::Migration[5.1]
  def change
    create_table :binda_relationships do |t|
      t.integer :parent_related_id
      t.integer :children_related_id
      t.string :parent_related_type
      t.string :children_related_type
      t.timestamps
    end
    add_index :binda_relationships, :parent_related_id
    add_index :binda_relationships, :children_related_id
  end
end`
`class CreateBindaRelatedFields < ActiveRecord::Migration[5.1]
  def change
    create_table :binda_related_fields do |t|

      t.string :name, null: false, uniqueness: true
      t.string :slug, null: false, uniqueness: true
      t.integer :field_setting_id
      t.integer :fieldable_id
      t.string :fieldable_type

    end

    add_index :binda_related_fields, :slug
  end
end
`

**Comment by thauma9** [comment]
`class CreateBindaRelationships < ActiveRecord::Migration[5.1]
  def change
    create_table :binda_relationships do |t|
      t.integer :parent_related_id
      t.integer :children_related_id
      t.string :parent_related_type
      t.string :children_related_type
      t.timestamps
    end
    add_index :binda_relationships, :parent_related_id
    add_index :binda_relationships, :children_related_id
  end
end`

**Pull request merged**
